### ISSUE TITLE
Data mismatch in rivm_NL_covid19_province.csv

### ISSUE THREAD

**Issue by ty525** [J535D165/CoronaWatchNL#100]
I see huge differences when comparing the data of 2020-05-03 and 2020-05-04. It looks like the updated numbers were mapped to the wrong provinces.

For example:

| - | - | -
-- | -- | --
2020-05-03 | Noord-Brabant | 8404
2020-05-04 | Noord-Brabant | 2912

![image](https://user-images.githubusercontent.com/13071306/80994632-ca5dc880-8df1-11ea-830d-d882291f17e5.png)

**Comment by J535D165** [comment]
Resolved. The format of the PDF's is changing every day at the moment. It would be nice to have a test for this.
