### ISSUE TITLE
Fix rendering of the maps in Actions

### ISSUE THREAD

**Issue by J535D165** [J535D165/CoronaWatchNL#11]
In the Github Actions workflow, the rendering of the maps fails. Unknown error to me, it works locally. It might be an idea to replace this by Python code.

**Comment by japhir** [comment]
Is this referring to the last bit of `plots.R`? For me locally it also doesn't run (after installing sf and all the secret libraries it needs but didn't tell me about, like gdal :angry:)

`Error: stat_sf requires the following missing aesthetics: geometry`

**Comment by japhir** [comment]
by adding `, geometry = geometry` to the aesthetics call it fixes it for me.
