### ISSUE TITLE
Animation of new cases 

### ISSUE THREAD

**Issue by J535D165** [J535D165/CoronaWatchNL#12]
It would be nice to have an animated map with the new cases per municipality. Is anyone interested in implementing?

It might be interesting to use the shapes of rivm: https://www.rivm.nl/media/bubbleMap/shapes/gemeente-2019.geojson

**Comment by J535D165** [comment]
TODO:

- still on last frame for a couple of seconds
- Add a color scale (dynamic?)

**Comment by lkleuver** [comment]
we have(had) this with the old RIVM data at https://coronb.caard.nl
our current version (https://corona.caard.nl) isn't very interesting to animate yet due to the data change.
