### ISSUE TITLE
new datasource - https://coronadashboard.rijksoverheid.nl/

### ISSUE THREAD

**Issue by Sikerdebaard** [J535D165/CoronaWatchNL#125]
This datasource might be interesting to add to CoronaWatchNL. Its the corona dashboard from the government. I think it is mostly interesting because it contains data around care-homes but also data regarding the reproduction number.

Unfortunately I don't have time to send in a PR for this at the moment.

It looks like the national data is encapsulated in a json: 
https://coronadashboard.rijksoverheid.nl/json/NL.json

There's also data on a per-veiligheids-regio level, which is encapsulated in jsons where the filename has the veiligheidsregio id in it.

Veiligheidsregio id's: https://www.rijksoverheid.nl/binaries/medium/content/gallery/rijksoverheid/content-afbeeldingen/ministeries/justitie-en-veiligheid/2020/kaartje-van-veiligheidsregios.png

JSON example URL for Rotterdam-Rijnmond:
https://coronadashboard.rijksoverheid.nl/json/VR17.json

JSON example URL for Groningen:
https://coronadashboard.rijksoverheid.nl/json/VR01.json

**Comment by J535D165** [comment]
Thanks, my colleague is working on this! https://github.com/J535D165/CoronaWatchNL/pull/124. We are happy to integrate more sources. 

Thanks for pointing out @Sikerdebaard

**Comment by J535D165** [comment]
We added 3 datasets. What sources are you interested in?
