### ISSUE TITLE
Hospitalizations municipalities to zero

### ISSUE THREAD

**Issue by Prikkel** [J535D165/CoronaWatchNL#131]
Hi,

I've noticed that for some municipalities, the latest data refresh (14-06-2020) has caused the amount of hospitalizations to drop to zero. 

Is this something that can still be fixed?

Kind regards,

Thomas

**Comment by J535D165** [comment]
We will have a look at this. Do you have an example?

Sorry for the inconvenience.

**Comment by Prikkel** [comment]
Hi Jonathan,

Thank you for the quick reply!

Two examples would be:
2020-06-13,402,Hilversum,Noord-Holland,27,31
2020-06-14,402,Hilversum,Noord-Holland,27,0

2020-06-13,546,Leiden,Zuid-Holland,28,39
2020-06-14,546,Leiden,Zuid-Holland,28,0

Kind regards,

Thomas

**Comment by J535D165** [comment]
Somehow, half of the dataset published yesterday. Luckily, your issue was in time, the full dataset is published and embedded in this repository now.
