### ISSUE TITLE
another attempt to show filterable / sortable gemeente-wise data in table / chart

### ISSUE THREAD

**Issue by shadkam** [J535D165/CoronaWatchNL#153]
Hi,

First of all .. thanks a lot for this effort.

I tried to put together [this page](https://shadkam.github.io/jsutils/html/covnl01.html), which makes use of data from https://github.com/J535D165/CoronaWatchNL/ ( specifically this file: https://raw.githubusercontent.com/J535D165/CoronaWatchNL/master/data/rivm_NL_covid19_total_municipality.csv  ).
It shows gemeente wise sortable tables / graphs .. gemeentees can be filtered, and date-range can be expanded / shrinked.
Hope this is OK .. to be making use of this file ( rivm_NL_covid19_total_municipality.csv ).

Also, if it is OK, may be a link to this page ( or, maybe the page itself ([src at github](https://github.com/shadkam/jsutils/blob/master/html/covnl01.html)) ) can be added to  /J535D165/CoronaWatchNL/ itself 

thanks
shadkam

**Comment by J535D165** [comment]
Nice, this looks very smooth! Feel free to drop your work on this page by creating a PR: https://github.com/J535D165/CoronaWatchNL/tree/master/applications.
