### ISSUE TITLE
Weekly stats on numbers of tests not updated

### ISSUE THREAD

**Issue by goedzo** [J535D165/CoronaWatchNL#158]
Weekly RIVM report has new test numbers: https://www.rivm.nl/sites/default/files/2020-09/COVID-19_WebSite_rapport_wekelijks_20200915_1433_NICEedit.pdf

Tabel 14: Aantal geteste personen en aantal SARS-CoV-2 positief geteste personen inNederland, gemeld door laboratoria, per week
.....
2020-09-07 -   2020-09-13     54     182964    5968    3.3
---

However, data is not updated in this file:
https://github.com/J535D165/CoronaWatchNL/blob/master/data-misc/data-test/RIVM_NL_test_latest.csv

**Comment by zwakhall** [comment]
Wrong date for data on Week 37. It says September 1. 2020 instead of September 7. 2020

**Comment by J535D165** [comment]
Fixed. I really need to write a unit test on this one. Too many mistakes. I'm sorry.

**Comment by zwakhall** [comment]
Nice! Thx. 
FYI: I use this data in https://www.iviz.nl/corona

**Comment by J535D165** [comment]
Nice work. Feel free to drop a link in our applications folder.

**Comment by goedzo** [comment]
Waiting a week for merge: https://github.com/J535D165/CoronaWatchNL/pull/168
