### ISSUE TITLE
Sewage water graph lagging behind with data

### ISSUE THREAD

**Issue by PanderMusubi** [J535D165/CoronaWatchNL#161]
Please (automatically) update sewage water graph which now goes until third week of August while there is data until mid September.

**Comment by J535D165** [comment]
Oke, I do have to update the graphs asap. 

Check out this issue as well https://github.com/minvws/nl-covid19-data-dashboard/issues/255.  I think it is unrelated, so just  for reference.

**Comment by J535D165** [comment]
I think it is resolved. Please do let me know if you think otherwise.
