### ISSUE TITLE
CoronaWatchNL/data-ic/data-nice/ - datasets are empty 

### ISSUE THREAD

**Issue by fmeijers** [J535D165/CoronaWatchNL#169]
Hi, 

I thankfully use your datasets from NICE. 

I notice that both tables on CoronaWatchNL/data-ic/data-nice/    are empty. They show the value 0 for all variables on all days

That is the case since October 6.

I hope you will be able to retrieve the data from Nice again soon.

Thanks in advance!
Frank

**Comment by J535D165** [comment]
@Sikerdebaard

We will have a look asap. Thanks for reporting.

**Comment by J535D165** [comment]
I think this was a glitch on the side of NICE. It works again. I will have a check at 4 PM (when the new data is collected by our project) to make sure everything works as expected.

**Comment by fmeijers** [comment]
Thanks it works!
