### ISSUE TITLE
Sigmoid plotting fails

### ISSUE THREAD

**Issue by J535D165** [J535D165/CoronaWatchNL#17]
The plotting of the sigmoid fails with the latest data @vmenger 

```
Sys.setlocale(category="LC_ALL", locale = "en_US.UTF-8")
Inflection expected after 15.6 days, at date 13/03/2020 13:00
/Users/jonathan/.pyenv/versions/anaconda3-2018.12/lib/python3.7/site-packages/pandas/plotting/_matplotlib/converter.py:103: FutureWarning: Using an implicitly registered datetime converter for a matplotlib plotting method. The converter was registered by pandas on import. Future versions of pandas will require you to explicitly register matplotlib converters.

To register the converters:
	>>> from pandas.plotting import register_matplotlib_converters
	>>> register_matplotlib_converters()
  warnings.warn(msg, FutureWarning)
Traceback (most recent call last):
  File "/Users/jonathan/Dropbox/Projects/Corona/CoronaWatchNL/python_plots.py", line 287, in <module>
    inflection_y = compute_inflection_cases(df, inflection_x)
  File "/Users/jonathan/Dropbox/Projects/Corona/CoronaWatchNL/python_plots.py", line 158, in compute_inflection_cases
    upper_bound = df[df['Dag'] == math.ceil(inflection_x)].iloc[0]['Aantal']
  File "/Users/jonathan/.pyenv/versions/anaconda3-2018.12/lib/python3.7/site-packages/pandas/core/indexing.py", line 1424, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/Users/jonathan/.pyenv/versions/anaconda3-2018.12/lib/python3.7/site-packages/pandas/core/indexing.py", line 2157, in _getitem_axis
    self._validate_integer(key, axis)
  File "/Users/jonathan/.pyenv/versions/anaconda3-2018.12/lib/python3.7/site-packages/pandas/core/indexing.py", line 2088, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
[Finished in 3.5s with exit code 1]
```

**Comment by japhir** [comment]
While it doesn't "fail" anymore, the fit has become very very bad. Any idea what's going on?

**Comment by J535D165** [comment]
@rensvandeschoot points to this post. Might be interesting http://www.casperalbers.nl/nl/post/2020-03-11-coronagrafieken/

**Comment by vmenger** [comment]
The fitting procedure based on estimating the inflection point turns out not to be so optimal. Especially estimating the number of cases at the inflection point is unreliable. Working on a better version right now!

**Comment by vmenger** [comment]
Ok, I have now fitted a 3-parameter logistic curve without the inflection point based on this manual (linked in the blog post of Casper Albers). Looks way better. Will make the PR now!

**Comment by japhir** [comment]
@vmenger could you also update the readme to explain the better fitting approach?

**Comment by J535D165** [comment]
Many thanks, folks. A great example of open science.

**Comment by japhir** [comment]
Yes, great work @vmenger :).

We might have to add some further caveats to the README, so that people who see these graphs without any context know that they are very very simple models, whose predictions are very likely very wrong.
I read [this long article](https://medium.com/@tomaspueyo/coronavirus-act-today-or-people-will-die-f4d3d9cd99ca) today that highlights how the number of "real" cases relates to the number of positively identified cases, and what this means for what we should be doing about it. Very informative!

**Comment by vmenger** [comment]
I'll see if I can find some time to update the Readme tomorrow.
