### ISSUE TITLE
Contagious data not up to date

### ISSUE THREAD

**Issue by realrolfje** [J535D165/CoronaWatchNL#170]
https://github.com/J535D165/CoronaWatchNL/tree/master/data-dashboard/data-contagious
is 13 days old

**Comment by Sikerdebaard** [comment]
This data comes from the rivm. The newest number released by them is from September 25th. I guess we have to wait until rivm releases new data? 

https://data.rivm.nl/geonetwork/srv/dut/catalog.search#/metadata/097155aa-75eb-4caa-8ed3-4c6edb80467e?tab=relations

**Comment by realrolfje** [comment]
Yes I noticed that the coronadashboard.nl has the same problem. I've mailed them about this issue, I think this estimate could (should) be a daily estimate, given the current circumstances.
Thanks for providing shit repo!

**Comment by J535D165** [comment]
Thanks for reporting. I will close this issue for now. Let's see when RIVM starts publishing this data again (very concerning that especially this number is not available for weeks now..)

**Comment by realrolfje** [comment]
Antwoord van RIVM:

> Deze week is er voor het schatten van het aantal besmettelijke personen overgegaan op nieuw beschikbare data. Hier is een alinea aan gewijd in het nieuwsbericht van afgelopen dinsdag (https://www.rivm.nl/nieuws/verspreiding-nieuwe-coronavirus-gaat-onverminderd-door) en dit wordt verder toegelicht in het wekelijks gepubliceerde rapport, op pagina 39. De tekst die hier te vinden is:
> 
> Vanaf 8 oktober gebruiken we serologische gegevens uit de tweede Pienter-Coronastudie van het RIVM zie hier. In deze studie zijn begin juni antistoffen bepaald in een willekeurige steekproef van de Nederlandse bevolking. Vóór 8 oktober gebruikten we de gegevens uit de eerste PienterCoronastudie, van begin april. Tussen 12 juni en 8 oktober werd het aantal besmettelijken ook gebaseerd op het aantal meldingen omdat de ziekenhuisopnames erg laag waren; deze stap wordt nu achterwege gelaten.
> 
> Om deze overgang soepeler te laten verlopen is ervoor gekozen om in de week ervoor geen nieuwe update te plaatsen van het aantal besmettelijke personen. Dit verklaart waarom de schatting wat langer op ongeveer 146.000 stond. Normaal gesproken wordt dit wekelijks geüpdatet, een dagelijkse update daarvoor is helaas niet mogelijk.
>
