### ISSUE TITLE
Extract Settings data from report to JSON

### ISSUE THREAD

**Issue by goedzo** [J535D165/CoronaWatchNL#171]
Since June 30, the weekly report includes settings data (the "location origin" where an infection has been been found. E.g. https://github.com/J535D165/CoronaWatchNL/blob/master/reports/COVID-19_epidemiological_report_20200630.pdf table 6.

This is very helpful data in inspecting measures vs the effect. Is it possible that the extraction of this data can be done from the PDF's and stored in a nice JSON file?
![afbeelding](https://user-images.githubusercontent.com/23582713/95842615-099c2800-0d47-11eb-8b6a-5168eb84526c.png)

**Comment by J535D165** [comment]
This makes sense to digitalize this table. Especially the "Sinds 4 mei" column.  

Let's parse this into something like this: https://github.com/J535D165/CoronaWatchNL/tree/master/data-misc/data-underlying/data-underlying_statistics

**Comment by goedzo** [comment]
Please note that the "sinds 4 mei" column changes its dates in following reports. No idea why though.
