### ISSUE TITLE
Ziekenhuisopname empty in RIVM data

### ISSUE THREAD

**Issue by Sikerdebaard** [J535D165/CoronaWatchNL#174]
The ziekenhuisopname seems to be empty in this dataset: https://github.com/J535D165/CoronaWatchNL/blob/master/data/rivm_NL_covid19_national_by_date/rivm_NL_covid19_national_by_date_latest.csv

Is there a reason for it to be empty? :)

**Comment by J535D165** [comment]
Unfortunately, the data is no longer available in the PDFs (As far as I know). In the past, we had a hard time reconstructing this data from the open data entry point. So what should we do?

**Comment by Sikerdebaard** [comment]
Ah I see. That is unfortunate.

Could the number of hospitalized be extrapolated from here? Since cumulative Ziekenhuisopname seems to work in this dataset? https://raw.githubusercontent.com/J535D165/CoronaWatchNL/master/data/rivm_NL_covid19_national.csv

If not I'll just remove it from covid-analytics.nl. There's enough alternative sources after all (LCPS / Stichting NICE.)

**Comment by goedzo** [comment]
Also not included here: https://raw.githubusercontent.com/J535D165/CoronaWatchNL/master/data/rivm_NL_covid19_age.csv

**Comment by Sikerdebaard** [comment]
`import pandas as pd

df = pd.read_json('https://data.rivm.nl/covid-19/COVID-19_aantallen_gemeente_cumulatief.json')

df['Date_of_report'] = pd.to_datetime(df['Date_of_report'])
df = df.set_index('Date_of_report')

df_daily = df.resample('D').sum().diff()
df_daily = df_daily.iloc[1:]

for col in df_daily.columns:
    df_daily[col] = df_daily[col].astype(int)
    
df_daily.rename(columns={'Total_reported': 'infected', 'Hospital_admission':  'hospitalized', 'Deceased': 'deceased'}, inplace=True)
df_daily.index.rename('date', inplace=True)

df_daily.to_csv('rivm_daily.csv')

df_weekly = df_daily.resample('W-MON', label='left').sum()
df_weekly.index = df_weekly.index.week
df_weekly.index.rename('week', inplace=True)
df_weekly.to_csv('rivm_weekly.csv')

print(df_daily)
print(df_weekly)`

This snippet seems to do the trick. It calculates it from the cumulative RIVM numbers. We lose the first day of data this way though, but that could be backfilled manually?
