### ISSUE TITLE
LCPS now publishes a CSV with it's data

### ISSUE THREAD

**Issue by Sikerdebaard** [J535D165/CoronaWatchNL#184]
So LCPS now has a csv file with it's data. It does not contain the hospitalized in germany data unfortunately, but it's definitely a good step forward. :+1: 

https://lcps.nu/datafeed/

**Comment by J535D165** [comment]
Thanks, @Sikerdebaard for pointing out, this a major step forward. 

What do you think about all the differences? 

https://lcps.nu/39-covid-patienten-op-ic/ reports 39, the CSV reports 36. This happens quite often. (btw the URLs of the news items are funny). 

I like the new variables and I will have a look at integrating this into our dataset.

**Comment by rcsmit** [comment]
Where can I find the 'opnames' before the 17th of October 2020?
