### ISSUE TITLE
Logarithmic plot doesn't seem to update

### ISSUE THREAD

**Issue by japhir** [J535D165/CoronaWatchNL#24]
It still shows points until the 13th, should it be included in some python pipe to update it as well? :).

**Comment by J535D165** [comment]
Thanks for reporting. I don't see the code where this plot is generated. Maybe some issues with the rebase? 

This plot is not listed in the readme isn't it? https://github.com/J535D165/CoronaWatchNL/blob/master/plots/growth_rate_time.png

**Comment by japhir** [comment]
regarding the growth rate plot: no it's not in the README, it was me trying to convert @vmenger's code to R so I understood what he was doing ;-).
