### ISSUE TITLE
Power BI report for RIVM Corona dataset

### ISSUE THREAD

**Issue by mvanreek** [J535D165/CoronaWatchNL#27]
Hi Jonathan,

As discussed by email, you can share my Power BI report for RIVM Corona dataset on your GitHub page, maybe with a reference to my blog-post (where I just uploaded v2 of the report)

https://worktimesheet2014.blogspot.com/2020/03/coronovirus-in-netherlands-power-bi.html
http://tiny.cc/ncwblz

regards,

Maarten van Reek
mvanreek@gmail.com

**Comment by J535D165** [comment]
Thanks, Done

**Comment by mvanreek** [comment]
where can I find it?

Op ma 16 mrt. 2020 om 08:49 schreef Jonathan de Bruin <
notifications@github.com>:

**Comment by J535D165** [comment]
Made a section with "interesting links" https://github.com/J535D165/CoronaWatchNL#interesting-links. It might be a bit hidden, but the data needs to be the main focus of the repo. 

Are you interested in making a list of fatalities to add to the repo? I'm too busy to work on it right now (I'm working on a large scientific project regarding corona).

**Comment by mvanreek** [comment]
Ok, I saw the link, thanks.
I'm afraid I also don't have enough time to work on adding fatalities. I'm not even sure if RIVM offers this data?
