### ISSUE TITLE
Add plots on fatalities and hospitalised patients

### ISSUE THREAD

**Issue by J535D165** [J535D165/CoronaWatchNL#31]
New datasets have been added. It would be nice to have plots on these numbers as well. 

@japhir

**Comment by japhir** [comment]
What do you reckon, new descriptive plot enough? Or should we include this in the simple model fitting as well? I think we'd best not…

**Comment by japhir** [comment]
Oh and I was also messing around with a simple column graph (or bar graph) but this results in stacked counts for `infected`, `hospitalized`, and `deceased`. Do you know if the deceased patients are subtracted from the `infected` counts?

**Comment by J535D165** [comment]
I think we can close this one :) 

> Do you know if the deceased patients are subtracted from the infected counts?
No, they aren't. They are counting positive tests only.

**Comment by japhir** [comment]
@J535D165 I've created another version in [my branch](https://github.com/japhir/CoronaWatchNL/blob/pimpplots/readmes/descriptive_plots.md) using bar graphs and switching from geom_rect to geom_rug for the timeline annotations. I'm not sure which one I prefer. What do you think?
