### ISSUE TITLE
Error in dataset on e.g. row 18

### ISSUE THREAD

**Issue by patfee** [J535D165/CoronaWatchNL#33]
in file rivm_corona_in_nl.csv i notice some lines which dont specify a "gemeenten". Like e.g. row 18
2020-03-02 |   | -1 |   | 8 -- | -- | -- | -- | --

There a few more of these.

How should i interpret these lines please?

Thanks
PAtrick

**Comment by J535D165** [comment]
These are the number of patients with an unknown municipality of residence. This number slightly increases over time. 

TODO: add a note to the readme

**Comment by J535D165** [comment]
Can anyone add a couple of lines on this?

**Comment by japhir** [comment]
This should probably be added to the [provincial](https://github.com/J535D165/CoronaWatchNL/tree/master/data-geo#provincial) and [municipal](https://github.com/J535D165/CoronaWatchNL/tree/master/data-geo#municipal) sections of the [data-geo workbook](https://github.com/J535D165/CoronaWatchNL/tree/master/data-geo), right?

**Comment by J535D165** [comment]
@RVoor can you work on this?

**Comment by RVoor** [comment]
Good point! I've added a footnote in the data-geo codebook.
