### ISSUE TITLE
growth rate in % over last n days 

### ISSUE THREAD

**Issue by Hazedd** [J535D165/CoronaWatchNL#34]
i have made some graphs in ArcGIS Pro, maybe intresting to generate on daily basis (and not in ArcGIS)?

working on a api endpoint that trows a html folium map 
todo:
- [ ] timeslider
- [x] geojson & style function instead of choropleth map
- [ ] chart popup 
- [ ] splitmap
- [ ] data annotation

preview:
[http://hazedd.pythonanywhere.com/coronaWatchNL/map
](http://hazedd.pythonanywhere.com/coronaWatchNL/map)

last 3 days:
![image](https://user-images.githubusercontent.com/20663495/77260337-8ec6cf00-6c87-11ea-8d06-2baa33626bb9.png)

last 7 days:
![image](https://user-images.githubusercontent.com/20663495/77260360-aef68e00-6c87-11ea-8253-b6c8bf9b3228.png)

last 14 days:
![image](https://user-images.githubusercontent.com/20663495/77260376-d8171e80-6c87-11ea-861e-3526f58b338c.png)

**Comment by J535D165** [comment]
Nice plots. Do you have Python skills? The draft is already there (map gifs). Not that hard to adjust.

**Comment by Hazedd** [comment]
Some skills.. Just used arcgis pro for visuals. Can do a remake of the map gifs and add a 3 day growth rate animation.

**Comment by Hazedd** [comment]
@J535D165 still few todo's be there is some progress.
[coronaWatchNLapi](https://github.com/Hazedd/CoronaWatchNL)

**Comment by Hazedd** [comment]
allmost.....
todo:
splitmap
timeslider

![image](https://user-images.githubusercontent.com/20663495/77587155-a7352480-6ee7-11ea-84ec-873bab90ed81.png)

![image](https://user-images.githubusercontent.com/20663495/77587244-d481d280-6ee7-11ea-86e0-e4f215eb5403.png)

![image](https://user-images.githubusercontent.com/20663495/77587310-f0857400-6ee7-11ea-9fc1-9dfafe088967.png)

**Comment by Hazedd** [comment]
update, hope i can do some more this weekend..

[http://hazedd.pythonanywhere.com/coronaWatchNL/map](http://hazedd.pythonanywhere.com/coronaWatchNL/map)

**Comment by Hazedd** [comment]
issue closed: folium abandoned.
