### ISSUE TITLE
Also update the graph thumbnails automatically?

### ISSUE THREAD

**Issue by japhir** [J535D165/CoronaWatchNL#37]
Maybe we could write a very short imagemagick script to put all the plots together and resize them?

**Comment by japhir** [comment]
A little:
```
convert +append timeline.png top_municipalities.png province_count_time.png -resize 1000 static/static_descriptive.png
```
should do it!

**Comment by vmenger** [comment]
That would be very nice IMO. Perhaps also rename it to thumbnail_descriptive.png or something similar as it is no longer static?

**Comment by J535D165** [comment]
Great, I did some work on this. I will push some results somewhere today!

**Comment by vmenger** [comment]
Can this be closed or is it still work in progress? @J535D165
