### ISSUE TITLE
Confirmed cases by sex and age

### ISSUE THREAD

**Issue by 4tikhonov** [J535D165/CoronaWatchNL#39]
I've discovered RIVM recently published data on COVID-19 cases by sex and age, and also a distribution by GGD district:
https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_the_Netherlands

Any plans to incorporate the data in the repository?

**Comment by J535D165** [comment]
I did add a dataset with ages. https://github.com/J535D165/CoronaWatchNL/blob/master/data/rivm_NL_covid19_age.csv

Let's team up to fix the other ones as well.

**Comment by J535D165** [comment]
sex is now available as well :)
