### ISSUE TITLE
Commit deleted the data from 2020-03-31 in rivm_corona_in_nl_daily.csv

### ISSUE THREAD

**Issue by patrborn** [J535D165/CoronaWatchNL#47]
Last commit deleted the data from 2020-03-31 (12595) 

https://github.com/J535D165/CoronaWatchNL/commit/a450b7cc79670ee3b329a8a3d28badfcd97cd3e9#commitcomment-38181311

**Comment by patrborn** [comment]
Too bad you have closed this issue. You can also see the result of the missing day 2020-03-31 in your own plots:

https://github.com/J535D165/CoronaWatchNL/raw/master/plots/overview_plot.png

https://github.com/J535D165/CoronaWatchNL/raw/master/plots/overview_plot_diff.png

**Comment by J535D165** [comment]
Sorry, this was by mistake. I'm a bit tired ;)

**Comment by J535D165** [comment]
Fixed. Sorry and please keep reaching out. It was a challenge yesterday because of all of the changes by RIVM.

**Comment by patrborn** [comment]
Thanks for all the effort you put into it

**Comment by GlobalConservationist** [comment]
Thanks for all your effort! The data from the 31st seems incorrect though? Many municipalities have lower numbers than the days before?
