### ISSUE TITLE
Two extra gaphs on timeline

### ISSUE THREAD

**Issue by PanderMusubi** [J535D165/CoronaWatchNL#50]
Can https://raw.githubusercontent.com/J535D165/CoronaWatchNL/master/plots/timeline.png also show 1) the total number of tests (first test positive + first test negative) and 2) the number of people that have recovered and subsequently tested negative (confirmation test negative).

**Comment by J535D165** [comment]
> 1) the total number of tests (first test positive + first test negative)

This data is in the reports nowadays, but we didn't standardize it yet. It would be interesting. 

> 2) the number of people that have recovered and subsequently tested negative (confirmation test negative).

Is this data available? I don't think so. Please point me to the source if it is. 

@japhir made this graph. What are your toughts?

**Comment by PanderMusubi** [comment]
When adding line 1 to the graph, all lines are each time a smaller number. Hence, don't add only first test negative as a separate line.

for 2: on the Guardian is reported how many people have recovered globally. No idea where they got this info.

**Comment by japhir** [comment]
I think it might be a cool separate plot, with time on the x-axis and a cumulative area chart with "tests" on the y filled with "positive" and "negative". This would illustrate our targeted testing quite well. Ideal data format would be:

| date             | result      | amount |
|----------------|-------------|-----------|
| 2020-04-02 |  positive | 2300 |
 
(made-up number)

**Comment by japhir** [comment]
> When adding line 1 to the graph, all lines are each time a smaller number. Hence, don't add only first test negative as a separate line.

I don't quite understand this. Misschien in het Nederlands? ;-).

**Comment by PanderMusubi** [comment]
Van hoog naar laag gerapporteerd zou er te zien zijn:
- aantal tests
- aantal besmettingen
- aantal hospitalisaties
- aantal overleden personen

**Comment by japhir** [comment]
I would like to add this but can't find the data on the number of tests that were conducted anywhere.

**Comment by vmenger** [comment]
Here is some data available: 

https://www.rivm.nl/coronavirus-covid-19/informatie-voor-professionals/virologische-dagstaten

Perhaps there is more in the pdf reports? 

See also:

https://twitter.com/jessefrederik/status/1247053915247579138

**Comment by J535D165** [comment]
This info can be found in the PDF documents. I was working on extracting the tables from the pdf. But they have 3 versions of this report. Every day, the use another... My regular expressions are not robust enough at the moment. 

On the website of RIVM are now new graphs WITH data available. I do expect more data will become available in the upcoming days. 

This project.....

**Comment by J535D165** [comment]
Thanks for reporting. This was implemented last week.
