### ISSUE TITLE
Trailing space char in `rivm_corona_in_nl_hosp.csv` for 2020-04-03 amount

### ISSUE THREAD

**Issue by dstotijn** [J535D165/CoronaWatchNL#54]
On https://github.com/J535D165/CoronaWatchNL/blob/3d5af4d47ef6354b82e211f0e4fe47694bd49449/data/rivm_corona_in_nl_hosp.csv#L24, there's a trailing space character after the amount, e.g. `6286 ` instead of `6286`.

**Comment by J535D165** [comment]
Good catch. Resolved.
