### ISSUE TITLE
Reactivate dataset rivm_corona_in_nl.csv

### ISSUE THREAD

**Issue by J535D165** [J535D165/CoronaWatchNL#57]
There is data on COVID-19 case counts on the municipality level available again. We can reactivate https://github.com/J535D165/CoronaWatchNL/blob/master/data/rivm_corona_in_nl.csv. See issue #44. I'm not sure whether this was by mistake or something they will provide on a daily basis. See https://github.com/J535D165/CoronaWatchNL/blob/master/raw_data/peildatum-08-04-2020-13-55.csv

**Comment by GlobalConservationist** [comment]
Great!

**Comment by mvanreek** [comment]
I have checked the RIVM csv files these days, and it is "In het ziekenhuis opgenomen COVID-19 patiënten", so hospitalizations, not positive-tested cases, so the file of 8/4 was probably a mistake. But as it seems they still track this data, why don't they just publish this data as a 2nd CSV file...

**Comment by J535D165** [comment]
@mvanreek The data is available for 8-9-10. We aren't expecting changes over the weekend. So I made a new dataset with this data: https://github.com/J535D165/CoronaWatchNL/blob/master/data/rivm_NL_covid19_total_municipality.csv

One remark, I have to add the missing values.
