### ISSUE TITLE
Contact with RIVM 

### ISSUE THREAD

**Issue by J535D165** [J535D165/CoronaWatchNL#58]
Hi all, 

First of all, thank you all for contributing to this repository. It is a challenge to keep up-to-date with all the daily changes on the RIVM website. Without your contributions, it isn't possible to keep this up-to-date and add new datasets. 

There are quite some questions regarding our contacts with RIVM and our offer to help them set up a proper data repository. We, CoronaWatchNL and Utrecht University, had contact with several people of RIVM. Unfortunately, there is no progress yet. More and more (prominent) researchers are teaming up with this project. They help us convincing RIVM to set up a data repository and use our/your expertise.

If there is anything to share, please drop it in this thread or send me an email at j.debruin1@uu.nl.

**Comment by Sikerdebaard** [comment]
First of all: thanks for doing the work.

Just dropping a message to let you know you are not alone in this. We are trying to get this data at Erasmus MC as well. Getting that data out in a machine readable format seems to be rather difficult. Not sure why.

What's more disturbing though is that Stichting NICE is becoming more unfriendly towards the general public. They are now blocking requests from ip adresses outside the Netherlands, which is a temporary stop-gap to reduce load. In the replies we have thus far received they state that their current focus is mostly on generating reports for RIVM, VWS and IC-regions, which is understandable, but I really really hope they won't take their public charts / api's offline due to server load.

**Comment by J535D165** [comment]
Our offer to help them will be discussed this week. 

In the meanwhile, it is important not to hammer the servers. There is no need for that if we team up in data collection projects. It reduces the workload on their side as well as our own workload. If we can join efforts, let me know.

**Comment by Sikerdebaard** [comment]
Cool, thanks. Please let them know we have a static website solution at the ready to mirror their public charts. We have reached out to them regarding this before, but they aren't taking it serious. The advantage of that specific solution is that once you put a CDN in front of it it scales extremely well.

**Comment by J535D165** [comment]
Update. 

RIVM is planning to make a well-structured dataset openly available. RIVM states that they aren't the owner of the data and have to ask permission to publish the data. They expect these issues to be solved anytime soon.

They consider the use of their open data platform https://statline.rivm.nl/. This platform is an implementation of [CBS Statline](https://opendata.cbs.nl/statline/#/CBS/nl/). Each dataset on this platform has an id that can be used for API requests. For example, table [50055NED](https://statline.rivm.nl/portal.html?_la=nl&_catalog=RIVM&tableId=50055NED&_theme=74). One can request the data with the Python package `cbsodata` (`pip install cbsodata`).

```python 
import cbsodata
import pandas as pd

cbsodata.options.catalog_url = 'dataderden.cbs.nl'

data = cbsodata.get_data("50055NED")

pd.DataFrame(data)
```

**Comment by herryklumper** [comment]
Is the corona data already available or is it just an example? I cannot find any

**Comment by J535D165** [comment]
According to RIVM, they will publish (more) structured data tomorrow. It was planned for today but was delayed due to some technical problems/challenges.

**Comment by herryklumper** [comment]
Hallo Jonathan,

Can you please explain where I can find the RIVM data on GitHub?
Or are you referring to the CSV on their own site?

Would it be possible through your contacts there to persuade them to create a robust repository on GitHub?

Thanks you
,

**Comment by J535D165** [comment]
RIVM published a structured dataset with the case counts per municipality. The publication and metadata can be found here: https://data.rivm.nl/geonetwork/srv/dut/catalog.search#/metadata/1c0fcd57-1102-4620-9cfa-441e93ea5604. This is the JSON API URL: https://data.rivm.nl/covid-19/COVID-19_aantallen_gemeente_cumulatief.json. 

The dataset receives updates at 4 PM. We asked them to publish this at 2 PM. Besides that, we asked them to backfill the data. 

RIVM states that they will publish more datasets soon. I will keep you posted.

**Comment by herryklumper** [comment]
Thank you. Happy that is under attention.

Met vriendelijke groet,
Herry Klumper
+31653428655
