### ISSUE TITLE
Create overview page with dashboards/website using CoronaWatchNL data

### ISSUE THREAD

**Issue by J535D165** [J535D165/CoronaWatchNL#59]
Thank you all for sending us emails with dashboards, visualizations, and gifs made with CoronaWatchNL data. We love to see them. 

At the moment, we are receiving a lot of emails on this and are having a hard time answering these emails. It might be an idea to make a separate page with an overview of these initiatives. (And integrate the Interesting links section of the README. Is there anyone interested in setting this up?

**Comment by jpvandervelden** [comment]
Is somebody already working on this issue?

**Comment by J535D165** [comment]
Hi @jpvandervelden, nope :( Interested?

**Comment by jpvandervelden** [comment]
Are you thinking about dashboards in the form of markdown pages? Like
national, regional?

**Comment by japhir** [comment]
Pull request #80 fixes this, so I'm closing the issue.
