### ISSUE TITLE
Include data with reporting lag per province

### ISSUE THREAD

**Issue by tdamsma** [J535D165/CoronaWatchNL#60]
The RIVM reports nicely show the data that is added per day, to make it clear that there is a significant lag in the reporting. However I did not find the source data published anywhere, a set that shows the reported cases/deaths/hospitalizations per reporting date and per date.

I took the liberty of extracting the data from the pdf reports. Data is [here](https://github.com/tdamsma/CoronaWatchNL/blob/plot-data-extraction/plot_data_extraction/data/hospitalizations_per_province.csv)

Please note that no individual reports are available before march 27th, so this shows in the graphs below.

![](https://github.com/tdamsma/CoronaWatchNL/raw/plot-data-extraction/plot_data_extraction/notebooks/plots/COVID%20Hospitalizations%20Netherlands%20by%20date%20reported.png)
[interactive](https://raw.githack.com/tdamsma/CoronaWatchNL/plot-data-extraction/plot_data_extraction/notebooks/plots/COVID%20Hospitalizations%20Netherlands%20by%20date%20reported.html)

![](https://github.com/tdamsma/CoronaWatchNL/raw/plot-data-extraction/plot_data_extraction/notebooks/plots/COVID%20Hospitalizations%20Netherlands%20by%20reporting%20lag.png) 
[interactive](https://raw.githack.com/tdamsma/CoronaWatchNL/plot-data-extraction/plot_data_extraction/notebooks/plots/COVID%20Hospitalizations%20Netherlands%20by%20reporting%20lag.html)

So now I made this, don't really know what to do with it. I can make a PR of course, but not sure how to structure the data for in here. Updating this requires a few minutes to export the data from the pdf graphs. Also I only did this for hospitalizations, not for the deaths/confirmed cases yet

**Comment by J535D165** [comment]
Nice, very nice. 

A stunning piece of reverse engineering... We are very happy to integrate the dataset in this repository. The source isn't available. The only thing I'm missing is the png extraction. How did you do this?

About the data storage, I think this type of data can be stored in this format: https://github.com/pcm-dpc/COVID-19/tree/master/dati-province. But, for now, your format is fine and intuitive. 

#59 It would be nice to work on this overview and expose your interactive dashboard over there. 

One suggestion, mark weekend days in your plot ;) This is a well-known issue in medical data.

**Comment by tdamsma** [comment]
All the code is available in github,in a few notebooks. See [this one](https://github.com/tdamsma/CoronaWatchNL/blob/plot-data-extraction/plot_data_extraction/notebooks/hospitalizations_extract_from_plots.ipynb) for the data extraction

**Comment by J535D165** [comment]
Thanks @tdamsma. Am I correct that this notebook requires PNG files as input? What did you do to extract the PNG's from the PDF?

(Hopefully, I'm not overlooking ;) )

**Comment by tdamsma** [comment]
Yep, unfortunately it does. I took screengrabs with Adobe acrobat at the maximum resolution. Also the scale factor from pixels to values is manually measured in mspaint. It's not pretty, but it works
