### ISSUE TITLE
Importing error Python

### ISSUE THREAD

**Issue by BasSchnater** [J535D165/CoronaWatchNL#63]
Hi all,

When I try to import the data into Python with Pandas, I keep hitting the same error:

> ParserError: Error tokenizing data. C error: Expected 1 fields in line 49, saw 2

Any suggestions how I can by pass this? Might be an easy question to answer but I haven't been able to find a solution that actually works :(

**Comment by BasSchnater** [comment]
Solved the issue myself: wasn't using the raw.githubusercontent link

**Comment by J535D165** [comment]
Thanks @BasSchnater, I think you aren't the first one struggling with this. I will add some notes to the README.md on this.
