### ISSUE TITLE
Broken link on homepage

### ISSUE THREAD

**Issue by wouterbeek** [J535D165/CoronaWatchNL#67]
The following link does not work ATM: <https://github.com/J535D165/CoronaWatchNL/blob/master/data/rivm_NL_covid19_national_by_date.csv>  If I click on it I get a 404.

It appears in the datasets table on the repository homepage with the name "COVID-19 case counts by date in NL (NEW)"

**Comment by J535D165** [comment]
Thanks for reporting. The problem is now resolved. Use the suffix 'latest' for the most recent version.
