### ISSUE TITLE
How to interpret the number of hospitalizations?

### ISSUE THREAD

**Issue by wouterbeek** [J535D165/CoronaWatchNL#70]
The maps for hospitalizations and infections look very different.  With hospitalizations the big cities light up:

![Screenshot from 2020-04-16 09-21-07](https://user-images.githubusercontent.com/1685012/79430460-3efacf80-7fc9-11ea-846a-59809a982a50.png)

With infections the areas where Corona is most widespread ATM light up:

![Screenshot from 2020-04-16 09-21-15](https://user-images.githubusercontent.com/1685012/79430468-415d2980-7fc9-11ea-999b-ebacc2bb0b1c.png)

I first thought that the hospitalizations are recorded for the municipality in which the hospital is located.  But this is not possible, because there are municipalities with no hospital that have a non-zero number.

What is the best way to interpret the number of hospitalizations?

**Comment by 4tikhonov** [comment]
Hi @wouterbeek, it looks great! Is it in your Linked Data infrastructure already?

**Comment by J535D165** [comment]
The location is the municipality of residence of the (hospitalized) patient according to RIVM. So you are right that there isn't a bias for hospital locations in NL. 

Variables you can into account: the average age in the municipality of residence and the number of residents per municipality (dividing hospitalizations by the number of residents might be tricky for small towns). 

I think this isn't a data quality concerns but a question regarding the interpretation, isn't it?

**Comment by wouterbeek** [comment]
@4tikhonov Yes, these are 'just' SPARQL queries over at <https://labs.kadaster.nl/stories/covid-19/>.

@J535D165 Yes indeed, we would like to have a good definition for each metric.  (Something we can add into the Linked Data schema to make the data self-desctiptive.)

**Comment by J535D165** [comment]
Hi @wouterbeek, We would love to work on this. What format do you prefer?

**Comment by wouterbeek** [comment]
@J535D165 A textual description would be sufficient.  We can copy/paste it into the Linked Data.

This is the identifier for hospitalizations: <https://data.labs.kadaster.nl/rivm/covid-19/vocab/hospitalizations>

![Screenshot from 2020-04-17 09-49-03](https://user-images.githubusercontent.com/1685012/79545312-c19a9200-8090-11ea-950f-d2d2dd1e3a7e.png)

In line with LD best practices, following the URI identifier gives a human- and machine-interpretable definition.

Also see [this SPARQL query](https://data.labs.kadaster.nl/rivm/-/queries/covid-19-overzicht), which retrieves the CoronaWatchNL tables that are currently represented in LD.  Each card displays a Data Structure Definition, which consists of dimensions (which allow observations to be identified) and measures (which register the observed values).

![Screenshot from 2020-04-17 09-52-26](https://user-images.githubusercontent.com/1685012/79545561-2b1aa080-8091-11ea-8680-6782ce8e2c05.png)

It would be nice to have good human-readable descriptions for all dimensions and measures.

Maybe we can publish the resulting vocabulary at CoronaWatchNL, or somewhere else, whichever makes more sense.

**Comment by J535D165** [comment]
Thanks. It might be a good idea to store the vocabulary here. I will start working on descriptions of the metrics and dimensions. I will keep you informed. Hopefully, you can help us with making this machine-readable.

**Comment by 4tikhonov** [comment]
@J535D165, can you please use the same codebook as Spanish and Italians?
https://github.com/datadista/datasets/tree/master/COVID%2019
https://github.com/pcm-dpc/COVID-19

It's very difficult to analyze data worldwide if it's not properly standardized.

**Comment by japhir** [comment]
I think this has been implemented now @4tikhonov, right? Closing the issue. Feel free to re-open if I misunderstood.
