### ISSUE TITLE
Double municipality records for the date 2020-04-17 and 2020-04-18

### ISSUE THREAD

**Issue by patrborn** [J535D165/CoronaWatchNL#75]
Something went wrong in making the following data files:
- rivm_NL_covid19_total_municipality.csv
- rivm_NL_covid19_hosp_municipality.csv

There are double municipality records for the date 2020-04-17 and 2020-04-18.

**Comment by patrborn** [comment]
Also for file rivm_NL_covid19_fatalities_municipality.csv for date 2020-04-18.

**Comment by J535D165** [comment]
Sorry :( Fixed. Thanks for reporting. 

I need to develop some test tools.
