### ISSUE TITLE
difference lcps and nice data

### ISSUE THREAD

**Issue by ErikEngerd** [J535D165/CoronaWatchNL#76]
Does anyone know what the difference is between the intakeCount in the nice dataset and the number of cases in the lcps dataset? In the media they use the lcps data and say it is the number of corona patients in the icu. The Rivm daily epidemiological report  calls it the confirmed covid-19 cases. Does this mean that the lcps data also includes suspected cases?

**Comment by RVoor** [comment]
I don't know that much about the lcps data, but I know the NICE IntakeCount represents "the number of suspected and proven COVID-19 cases present on the IC per day (see https://www.stichting-nice.nl/ for more information, figures, and detailed notes). This only regards the already present patients, and not the newly submitted patients per day. From the introduction of the epidemiological report (see below for citation), I deduce that the report only shows the proven COVID-19 cases. 

"Uitleg over Surveillance van COVID-19 patiënten in Nederland: Via een samenwerking tussen artsen, laboratoria en de GGD’en wordt informatie verzameld over personen (patiënten) met een positieve COVID-19 testuitslag. In het begin van de COVID-19 epidemie in Nederland werd veel getest, niet alleen."

**Comment by RVoor** [comment]
I don't know that much about the lcps data, but I know the NICE IntakeCount represents "the number of suspected and proven COVID-19 cases present on the IC per day" (see https://www.stichting-nice.nl/ for more information, figures, and detailed notes). This only regards the already present patients, and not the newly submitted patients per day. From the introduction of the epidemiological report (see below for citation), I deduce that the report only shows the proven COVID-19 cases.

"Uitleg over Surveillance van COVID-19 patiënten in Nederland: Via een samenwerking tussen artsen, laboratoria en de GGD’en wordt informatie verzameld over personen (patiënten) met een positieve COVID-19 testuitslag."

**Comment by Jeroenr1** [comment]
Not sure if this is still relevant, but i just noticed the following text on the NICE site:

> LCPS maakt dagelijks het aantal Nederlandse COVID-patiënten op de IC bekend in de media. Daarvoor baseert LCPS zich op de rapportage van het aantal COVID-patiënten in NICE. Ondanks de enorme inzet van de ziekenhuizen kan de registratie op patiënt-niveau bij sommige ziekenhuizen mogelijk iets achterlopen in NICE. Daarom maakt LCPS een schatting van de achterstand in registratie. Voor deze schatting gebruikt LCPS de informatie over het actuele aantal COVID-patiënten op geaggregeerd IC-niveau die ROAZ-regio’s dagelijks aan LCPS aanleveren. NICE blijft de belangrijkste bron en toont na verloop van tijd de meest betrouwbare gegevens.

Loosely translated this means that NICE is the official known number and in time the most accurate number. 
LCPS tries to guesstimate the most accurate number at the time of publication.

**Comment by ErikEngerd** [comment]
that is indeed what I also read a few days ago. The numbers reported by lcps are significantly higher than those by nice (even when it concerns data from a number of days ago). It is important to know that the media are reporting the lcps data and not those by nice. 

On 23 April 2020 14:39:35 CEST, Jeroen Rakhorst <notifications@github.com> wrote:
>Not sure if this is still relevant, but i just noticed the following
>text on the NICE site:>
>>
>> LCPS maakt dagelijks het aantal Nederlandse COVID-patiënten op de IC
>bekend in de media. Daarvoor baseert LCPS zich op de rapportage van het
>aantal COVID-patiënten in NICE. Ondanks de enorme inzet van de
>ziekenhuizen kan de registratie op patiënt-niveau bij sommige
>ziekenhuizen mogelijk iets achterlopen in NICE. Daarom maakt LCPS een
>schatting van de achterstand in registratie. Voor deze schatting
>gebruikt LCPS de informatie over het actuele aantal COVID-patiënten op
>geaggregeerd IC-niveau die ROAZ-regio’s dagelijks aan LCPS aanleveren.
>NICE blijft de belangrijkste bron en toont na verloop van tijd de meest
>betrouwbare gegevens.>
>>
>Loosely translated this means that NICE is the official known number
>and in time the most accurate number. >
>LCPS tries to guesstimate the most accurate number at the time of
>publication.>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/J535D165/CoronaWatchNL/issues/76#issuecomment-618378657

Erik Brakkee

**Comment by RVoor** [comment]
It's true that the numbers of reported by LCPS are consistently higher than the ones reported by NICE. Even though the LCPS's 'Aantal' describes the same als NICE's 'intakeCount' (i.e., number of (suspected) COVID-19 cases present on the IC per day), the LCPS also includes Dutch cases hospitalized in Germany while NICE only reports Dutch cases hospitalized in the Netherlands. This might explain the consistent difference in numbers.

**Comment by japhir** [comment]
Looks like the question has been addressed here. Should this distinction be added somewhere in the documentation? If so, feel free to create a PR. Closing this for now.

**Comment by ErikEngerd** [comment]
I think it is always a good idea to document what the data means and how it was obtained. 

On 5 May 2020 12:04:03 CEST, Ilja Kocken <notifications@github.com> wrote:
>Looks like the question has been addressed here. Should this
>distinction be added somewhere in the documentation? If so, feel free
>to create a PR. Closing this for now.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/J535D165/CoronaWatchNL/issues/76#issuecomment-623966022

Erik Brakkee

**Comment by J535D165** [comment]
Agree. We are welcoming PR's on this.
