### ISSUE TITLE
rivm_corona_in_nl_fatalities.csv double 27th April data

### ISSUE THREAD

**Issue by JJKuijvenhoven** [J535D165/CoronaWatchNL#89]
Hi,

rivm_corona_in_nl_fatalities.csv data contains two values of data for 27th of April. I guess the last row should contain 28th April data.

Best regards

**Comment by Rogiervanweert** [comment]
Yep i saw the same problem!

**Comment by patrborn** [comment]
It applies for the following files:
rivm_corona_in_nl_daily.csv
rivm_corona_in_nl_fatalities.csv
rivm_corona_in_nl_hosp.csv
rivm_NL_covid19_national.csv

**Comment by J535D165** [comment]
I'm so sorry. I made a fix. I really need to add more tests and automation... 

Please note that rivm_NL_covid19_national.csv is the main source and the other 3 files are pending deprecation.
