### ISSUE TITLE
Fit a logistic regression as well?

### ISSUE THREAD

**Issue by japhir** [J535D165/CoronaWatchNL#9]
Hi Jonathan,

After watching this epic video by 3blue1brown https://www.youtube.com/watch?v=Kas0tIxDvrg I thought you could perhaps fit a sigmoid line as well as the exponential.

Or even better (will probably only make sense if you've seen the video)
1. calculate the change per time step (current value - previous value)
2. calculate the growth rate (ratio of the current and previous change)
3. estimate when the above will be 1 (with another kind of fit?)
4. fit the sigmoid with that time as the inflection point :astonished:?

**Comment by J535D165** [comment]
Thanks, yes this video is great. Interested in doing a PR?

**Comment by japhir** [comment]
Yes, I'd be interested but unfortunately cannot take on any programming side projects right now, even though this sounds like fun. Last year of my PhD is about to begin 😅

**Comment by J535D165** [comment]
It might be a good idea to add a link to the video in the forecast section
