### ISSUE TITLE
Data missing in rivm_NL_covid19_hosp_municipality.csv and rivm_NL_covid19_total_municipality.csv?

### ISSUE THREAD

**Issue by JJKuijvenhoven** [J535D165/CoronaWatchNL#90]
Hi,

Before in 'rivm_NL_covid19_hosp_municipality.csv' and 'rivm_NL_covid19_total_municipality.csv' data for unknown municipalities/provinces was reported with a blank row. 

For example: 
Datum,Gemeentecode,Gemeentenaam,Provincienaam,Provinciecode,Aantal
2020-04-16,-1,,,,431

I identified that in the extract of today (28 April) that this is not reported anymore for both tables.
Datum,Gemeentecode,Gemeentenaam,Provincienaam,Provinciecode,Aantal
2020-04-28,-1,,,,

Is this missing data, or will this the new data format and unknow municipalities won't be reported anymore?

Thanks in advance!

**Comment by J535D165** [comment]
Thanks for keeping me awake. This was also a side effect of your other reported issue. 

I made a couple of changes on these datasets last weekend:

- every day has values for all municipalities. Not only for non-zero counts. 
- computing the missing values is now based on the national counts (this wasn't done before and therefore missing values were not reported in some cases).

You might be interested in using this dataset from now on: https://github.com/J535D165/CoronaWatchNL/tree/master/data-geo#municipal. It contains the values for all three types. 

@JJKuijvenhoven can you send me an email at jonathandebruinos@gmail.com?
