### ISSUE TITLE
Deaths per province

### ISSUE THREAD

**Issue by mirix** [J535D165/CoronaWatchNL#92]
Hello,

I have a question regarding the following file: 

https://github.com/J535D165/CoronaWatchNL/blob/master/data/rivm_NL_covid19_fatalities_municipality.csv

It starts on April 18th, is it possible to find earlier data?

I am doing this:

https://sentidinho.eu/sentidinho/wp-content/uploads/galiciaincoronavirusland/NUTS2_in_coronavirusland.html

Best regards,

Ed

**Comment by mirix** [comment]
Never mind. Sorry, I have realised it is cumulative data. It is alright. Thank you.

**Comment by J535D165** [comment]
Unfortunately, the data wasn't available on the municipality level before this date. There is an option to digitalize this for data on the provincial level, but this is work in progress (based on the PDF's).
